# Generated by Django 3.0.5 on 2022-12-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='hospital',
            field=models.CharField(default='Nothing', max_length=100),
        ),
    ]
