# Generated by Django 4.1.4 on 2022-12-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_blooddonate_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='disease',
            field=models.CharField(default='Patient name', max_length=100),
        ),
    ]
