# Generated by Django 4.1.4 on 2022-12-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_bloodrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital',
            field=models.CharField(default='Nothing', max_length=100),
        ),
    ]
